version: '2'
services:
  server:
    image: synesthesiam/rhasspy-server:latest
    environment:
      - RHASSPY_PROFILES=/profiles
      - RHASSPY_TTS_DIR=/tts
    volumes:
      - ./server/profiles:/profiles
      - ./server/tts:/tts
    ports:
      - "13202:12101"
  client:
    image: synesthesiam/rhasspy-server:latest
    environment:
      - RHASSPY_PROFILES=/profiles
      - RHASSPY_TTS_DIR=/tts
    volumes:
      - ./client/profiles:/profiles
      - ./client/tts:/tts
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "12101:12101"
  hass:
    image: homeassistant/home-assistant
    volumes:
      - ./home-assistant/config:/config
    ports:
      - "8123:8123"
