version: '2'
services:
  rhasspy:
    image: synesthesiam/rhasspy-server:latest
    network_mode: "host"
    volumes:
      - ./config/rhasspy/profiles:/profiles
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "12101:12101"
    command: --profile en --user-profiles /profiles
  hass:
    image: homeassistant/home-assistant
    network_mode: "host"
    volumes:
      - ./home-assistant/config:/config
    ports:
      - "8123:8123"
